// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from 'C:/Users/mel/Desktop/project/Black-Silder/node_modules/dumi/dist/client/theme-api/index.js';
