// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'C:/Users/mel/Desktop/project/Black-Silder/node_modules/dumi/theme-default/slots/HeroTitle/index.js';
