// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'C:/Users/mel/Desktop/project/black-slider/node_modules/dumi/theme-default/slots/PreviewerActionsExtra/index.js';
