// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/guide":{"path":"guide","id":"docs/guide","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/floating-ball/index":{"id":"components/floating-ball/index","path":"components/floating-ball","parentId":"DocLayout","meta":{"_atom_route":true}},"components/scroll-circle/index":{"id":"components/scroll-circle/index","path":"components/scroll-circle","parentId":"DocLayout","meta":{"_atom_route":true}},"components/slider-puzzle/index":{"id":"components/slider-puzzle/index","path":"components/slider-puzzle","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "dumi__pages__404" */'@/dumi__pages/404')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__ContextWrapper" */'@/dumi__theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__layouts__DocLayout" */'@/dumi__theme/layouts/DocLayout')),
'docs/guide': React.lazy(() => import(/* webpackChunkName: "docs__guide.md" */'C:/Users/mel/Desktop/project/black-slider/docs/guide.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'C:/Users/mel/Desktop/project/black-slider/docs/index.md')),
'components/floating-ball/index': React.lazy(() => import(/* webpackChunkName: "floating-ball__index.md" */'C:/Users/mel/Desktop/project/black-slider/src/floating-ball/index.md')),
'components/scroll-circle/index': React.lazy(() => import(/* webpackChunkName: "scroll-circle__index.md" */'C:/Users/mel/Desktop/project/black-slider/src/scroll-circle/index.md')),
'components/slider-puzzle/index': React.lazy(() => import(/* webpackChunkName: "slider-puzzle__index.md" */'C:/Users/mel/Desktop/project/black-slider/src/slider-puzzle/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "dumi__pages__Demo" */'@/dumi__pages/Demo')),
},
  };
}
